import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { ptBR } from "@clerk/localizations";
import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from 'sonner';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SnakeCase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={ptBR}>
      <html lang="pt-br">
        <body className={inter.className}>
          <Toaster richColors closeButton />
          <Navbar />

          <main className="flex flex-col min-h-[calc(100vh-3.5rem-1px)]">
            {children}

            <Footer />
          </main>

        </body>
      </html>
    </ClerkProvider>
  );
}
